services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama_server.rule=Host(`ollama.home.${DOMAIN}`)"
      - "traefik.http.routers.ollama_server.entrypoints=websecure"
      - "traefik.http.services.ollama_server.loadbalancer.server.port=11434"
      - "traefik.http.routers.ollama_server.service=ollama_server"
      - "traefik.http.routers.ollama_server.tls.certresolver=leresolver"

networks:
  proxy:
    external: true
volumes:
  ollama:
